### ISSUE TITLE
mSelectionsAll returns only an array of 6 selections

### ISSUE THREAD

**Issue by gangataarun** [countnazgul/enigma-mixin#18]
I am building a react mashup. While using mSelectionsAll to get my current selections, only the first 6 field selections are returned but I have a selection of more than 6 values

I would expect it to return all of the field selections.

**Comment by countnazgul** [comment]
I've just published beta version of the package (can be installed with `npm install enigma-mixin@beta`). 
In this version `mSelectionsAll` will return an object with two properties: `selections` and `selectedValues`

`selections` contains the same data as before
`selectedValues` contains an array with the fields selections and their values (the image below)

![image](https://user-images.githubusercontent.com/22850/110429960-969f9f00-80a3-11eb-9276-8108ae07951e.png)

(If you want only the `selectedValues` you can write something like this `let { selectedValues: whatever } = await qDoc.mSelectionsAll();`)

Ill keep this issue open for now. Have to make few more tests before publish the official (not `beta`) version

**Comment by countnazgul** [comment]
Published the final version - 0.1.2

Let me know if you are experiencing any issues

Thanks for the issue btw :)
