### ISSUE TITLE
npm install enigma-mixin instead of npm install enigma-mixins

### ISSUE THREAD

**Issue by SBylemans** [countnazgul/enigma-mixin#37]
**Describe the bug**
Documentation contains command for `npm install enigma-mixins`. This is not correct as it should be `npm install enigma-mixin`.

**To Reproduce**
1. Try running `npm install enigma-mixins`, does not work
2. Try running `npm install enigma-mixin`, does work

**Comment by countnazgul** [comment]
thank you very much for this! fixed
